# Generated by Django 5.0.6 on 2024-06-06 12:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_active_appuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/category_images/')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=800, verbose_name='Описание')),
                ('composition', models.TextField(blank=True, max_length=400, verbose_name='Состав')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='media/product_photos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
