# Generated by Django 5.0.6 on 2024-06-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Блок фотографий'),
        ),
    ]
