# Generated by Django 5.0.6 on 2024-06-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
