# Generated by Django 5.0.6 on 2024-06-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0011_alter_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
